Authentication git api
TheKafer/workshop-api-testing-js pull request #7
Opened 2020-12-17 19:05 UTC by TheKafer

2020-12-17 19:17 UTC, manuelq12 requested changes

2020-12-17 19:17 UTC, manuelq12 commented on test/GithubApi.Authentication.test.js
> +});
You didn't include the test to Authenticate by parameters

2020-12-18 13:02 UTC, danielgalvis98 approved these changes

2020-12-18 13:05 UTC, manuelq12 approved these changes

2020-12-18 13:08 UTC, merged